/**
 * India States & Districts Data
 * Comprehensive mapping for address form dropdowns
 */

export interface District {
  name: string;
  pincodePrefixes: string[]; // Possible pincode prefixes
}

export interface State {
  name: string;
  code: string;
  districts: District[];
}

export const INDIA_STATES: State[] = [
  {
    name: 'Andhra Pradesh',
    code: 'AP',
    districts: [
      { name: 'Anakapalli', pincodePrefixes: ['531'] },
      { name: 'Anantapur', pincodePrefixes: ['515'] },
      { name: 'Annamayya', pincodePrefixes: ['516'] },
      { name: 'Bapatla', pincodePrefixes: ['522'] },
      { name: 'Chittoor', pincodePrefixes: ['517'] },
      { name: 'Dr. B.R. Ambedkar Konaseema', pincodePrefixes: ['533'] },
      { name: 'East Godavari', pincodePrefixes: ['533'] },
      { name: 'Eluru', pincodePrefixes: ['534'] },
      { name: 'Guntur', pincodePrefixes: ['522'] },
      { name: 'Kakinada', pincodePrefixes: ['533'] },
      { name: 'Krishna', pincodePrefixes: ['521'] },
      { name: 'Kurnool', pincodePrefixes: ['518'] },
      { name: 'Nandyal', pincodePrefixes: ['518'] },
      { name: 'Nellore', pincodePrefixes: ['524'] },
      { name: 'NTR', pincodePrefixes: ['521'] },
      { name: 'Palnadu', pincodePrefixes: ['522'] },
      { name: 'Prakasam', pincodePrefixes: ['523'] },
      { name: 'Sri Sathya Sai', pincodePrefixes: ['515'] },
      { name: 'Srikakulam', pincodePrefixes: ['532'] },
      { name: 'Tirupati', pincodePrefixes: ['517'] },
      { name: 'Visakhapatnam', pincodePrefixes: ['530'] },
      { name: 'Vizianagaram', pincodePrefixes: ['535'] },
      { name: 'West Godavari', pincodePrefixes: ['534'] },
      { name: 'YSR Kadapa', pincodePrefixes: ['516'] },
    ],
  },
  {
    name: 'Arunachal Pradesh',
    code: 'AR',
    districts: [
      { name: 'Anjaw', pincodePrefixes: ['792'] },
      { name: 'Changlang', pincodePrefixes: ['792'] },
      { name: 'Dibang Valley', pincodePrefixes: ['792'] },
      { name: 'East Kameng', pincodePrefixes: ['790'] },
      { name: 'East Siang', pincodePrefixes: ['791'] },
      { name: 'Itanagar Capital Complex', pincodePrefixes: ['791'] },
      { name: 'Kamle', pincodePrefixes: ['791'] },
      { name: 'Kra Daadi', pincodePrefixes: ['791'] },
      { name: 'Kurung Kumey', pincodePrefixes: ['791'] },
      { name: 'Lepa Rada', pincodePrefixes: ['791'] },
      { name: 'Lohit', pincodePrefixes: ['792'] },
      { name: 'Longding', pincodePrefixes: ['792'] },
      { name: 'Lower Dibang Valley', pincodePrefixes: ['792'] },
      { name: 'Lower Siang', pincodePrefixes: ['791'] },
      { name: 'Lower Subansiri', pincodePrefixes: ['791'] },
      { name: 'Namsai', pincodePrefixes: ['792'] },
      { name: 'Pakke-Kessang', pincodePrefixes: ['790'] },
      { name: 'Papum Pare', pincodePrefixes: ['791'] },
      { name: 'Shi Yomi', pincodePrefixes: ['791'] },
      { name: 'Siang', pincodePrefixes: ['791'] },
      { name: 'Tawang', pincodePrefixes: ['790'] },
      { name: 'Tirap', pincodePrefixes: ['792'] },
      { name: 'Upper Siang', pincodePrefixes: ['791'] },
      { name: 'Upper Subansiri', pincodePrefixes: ['791'] },
      { name: 'West Kameng', pincodePrefixes: ['790'] },
      { name: 'West Siang', pincodePrefixes: ['791'] },
    ],
  },
  {
    name: 'Assam',
    code: 'AS',
    districts: [
      { name: 'Bajali', pincodePrefixes: ['781'] },
      { name: 'Baksa', pincodePrefixes: ['781'] },
      { name: 'Barpeta', pincodePrefixes: ['781'] },
      { name: 'Biswanath', pincodePrefixes: ['784'] },
      { name: 'Bongaigaon', pincodePrefixes: ['783'] },
      { name: 'Cachar', pincodePrefixes: ['788'] },
      { name: 'Charaideo', pincodePrefixes: ['785'] },
      { name: 'Chirang', pincodePrefixes: ['783'] },
      { name: 'Darrang', pincodePrefixes: ['784'] },
      { name: 'Dhemaji', pincodePrefixes: ['787'] },
      { name: 'Dhubri', pincodePrefixes: ['783'] },
      { name: 'Dibrugarh', pincodePrefixes: ['786'] },
      { name: 'Dima Hasao', pincodePrefixes: ['788'] },
      { name: 'Goalpara', pincodePrefixes: ['783'] },
      { name: 'Golaghat', pincodePrefixes: ['785'] },
      { name: 'Hailakandi', pincodePrefixes: ['788'] },
      { name: 'Hojai', pincodePrefixes: ['782'] },
      { name: 'Jorhat', pincodePrefixes: ['785'] },
      { name: 'Kamrup', pincodePrefixes: ['781'] },
      { name: 'Kamrup Metropolitan', pincodePrefixes: ['781'] },
      { name: 'Karbi Anglong', pincodePrefixes: ['782'] },
      { name: 'Karimganj', pincodePrefixes: ['788'] },
      { name: 'Kokrajhar', pincodePrefixes: ['783'] },
      { name: 'Lakhimpur', pincodePrefixes: ['787'] },
      { name: 'Majuli', pincodePrefixes: ['785'] },
      { name: 'Morigaon', pincodePrefixes: ['782'] },
      { name: 'Nagaon', pincodePrefixes: ['782'] },
      { name: 'Nalbari', pincodePrefixes: ['781'] },
      { name: 'Sivasagar', pincodePrefixes: ['785'] },
      { name: 'Sonitpur', pincodePrefixes: ['784'] },
      { name: 'South Salmara-Mankachar', pincodePrefixes: ['783'] },
      { name: 'Tamulpur', pincodePrefixes: ['781'] },
      { name: 'Tinsukia', pincodePrefixes: ['786'] },
      { name: 'Udalguri', pincodePrefixes: ['784'] },
      { name: 'West Karbi Anglong', pincodePrefixes: ['782'] },
    ],
  },
  {
    name: 'Bihar',
    code: 'BR',
    districts: [
      { name: 'Araria', pincodePrefixes: ['854'] },
      { name: 'Arwal', pincodePrefixes: ['804'] },
      { name: 'Aurangabad', pincodePrefixes: ['824'] },
      { name: 'Banka', pincodePrefixes: ['813'] },
      { name: 'Begusarai', pincodePrefixes: ['851'] },
      { name: 'Bhagalpur', pincodePrefixes: ['812'] },
      { name: 'Bhojpur', pincodePrefixes: ['802'] },
      { name: 'Buxar', pincodePrefixes: ['802'] },
      { name: 'Darbhanga', pincodePrefixes: ['846'] },
      { name: 'East Champaran', pincodePrefixes: ['845'] },
      { name: 'Gaya', pincodePrefixes: ['823'] },
      { name: 'Gopalganj', pincodePrefixes: ['841'] },
      { name: 'Jamui', pincodePrefixes: ['811'] },
      { name: 'Jehanabad', pincodePrefixes: ['804'] },
      { name: 'Kaimur', pincodePrefixes: ['821'] },
      { name: 'Katihar', pincodePrefixes: ['854'] },
      { name: 'Khagaria', pincodePrefixes: ['851'] },
      { name: 'Kishanganj', pincodePrefixes: ['855'] },
      { name: 'Lakhisarai', pincodePrefixes: ['811'] },
      { name: 'Madhepura', pincodePrefixes: ['852'] },
      { name: 'Madhubani', pincodePrefixes: ['847'] },
      { name: 'Munger', pincodePrefixes: ['811'] },
      { name: 'Muzaffarpur', pincodePrefixes: ['842'] },
      { name: 'Nalanda', pincodePrefixes: ['803'] },
      { name: 'Nawada', pincodePrefixes: ['805'] },
      { name: 'Patna', pincodePrefixes: ['800', '801'] },
      { name: 'Purnia', pincodePrefixes: ['854'] },
      { name: 'Rohtas', pincodePrefixes: ['821'] },
      { name: 'Saharsa', pincodePrefixes: ['852'] },
      { name: 'Samastipur', pincodePrefixes: ['848'] },
      { name: 'Saran', pincodePrefixes: ['841'] },
      { name: 'Sheikhpura', pincodePrefixes: ['811'] },
      { name: 'Sheohar', pincodePrefixes: ['843'] },
      { name: 'Sitamarhi', pincodePrefixes: ['843'] },
      { name: 'Siwan', pincodePrefixes: ['841'] },
      { name: 'Supaul', pincodePrefixes: ['852'] },
      { name: 'Vaishali', pincodePrefixes: ['844'] },
      { name: 'West Champaran', pincodePrefixes: ['845'] },
    ],
  },
  {
    name: 'Chhattisgarh',
    code: 'CG',
    districts: [
      { name: 'Balod', pincodePrefixes: ['491'] },
      { name: 'Baloda Bazar', pincodePrefixes: ['493'] },
      { name: 'Balrampur', pincodePrefixes: ['497'] },
      { name: 'Bastar', pincodePrefixes: ['494'] },
      { name: 'Bemetara', pincodePrefixes: ['491'] },
      { name: 'Bijapur', pincodePrefixes: ['494'] },
      { name: 'Bilaspur', pincodePrefixes: ['495'] },
      { name: 'Dantewada', pincodePrefixes: ['494'] },
      { name: 'Dhamtari', pincodePrefixes: ['493'] },
      { name: 'Durg', pincodePrefixes: ['490', '491'] },
      { name: 'Gariaband', pincodePrefixes: ['493'] },
      { name: 'Gaurela-Pendra-Marwahi', pincodePrefixes: ['495'] },
      { name: 'Jagdalpur', pincodePrefixes: ['494'] },
      { name: 'Janjgir-Champa', pincodePrefixes: ['495'] },
      { name: 'Jashpur', pincodePrefixes: ['496'] },
      { name: 'Kabirdham', pincodePrefixes: ['491'] },
      { name: 'Kanker', pincodePrefixes: ['494'] },
      { name: 'Kondagaon', pincodePrefixes: ['494'] },
      { name: 'Korba', pincodePrefixes: ['495'] },
      { name: 'Koriya', pincodePrefixes: ['497'] },
      { name: 'Mahasamund', pincodePrefixes: ['493'] },
      { name: 'Mungeli', pincodePrefixes: ['495'] },
      { name: 'Narayanpur', pincodePrefixes: ['494'] },
      { name: 'Raigarh', pincodePrefixes: ['496'] },
      { name: 'Raipur', pincodePrefixes: ['492', '493'] },
      { name: 'Rajnandgaon', pincodePrefixes: ['491'] },
      { name: 'Sakti', pincodePrefixes: ['495'] },
      { name: 'Sukma', pincodePrefixes: ['494'] },
      { name: 'Surajpur', pincodePrefixes: ['497'] },
      { name: 'Surguja', pincodePrefixes: ['497'] },
    ],
  },
  {
    name: 'Goa',
    code: 'GA',
    districts: [
      { name: 'North Goa', pincodePrefixes: ['403'] },
      { name: 'South Goa', pincodePrefixes: ['403'] },
    ],
  },
  {
    name: 'Gujarat',
    code: 'GJ',
    districts: [
      { name: 'Ahmedabad', pincodePrefixes: ['380', '382'] },
      { name: 'Amreli', pincodePrefixes: ['365'] },
      { name: 'Anand', pincodePrefixes: ['388'] },
      { name: 'Aravalli', pincodePrefixes: ['383'] },
      { name: 'Banaskantha', pincodePrefixes: ['385'] },
      { name: 'Bharuch', pincodePrefixes: ['392'] },
      { name: 'Bhavnagar', pincodePrefixes: ['364'] },
      { name: 'Botad', pincodePrefixes: ['364'] },
      { name: 'Chhota Udaipur', pincodePrefixes: ['391'] },
      { name: 'Dahod', pincodePrefixes: ['389'] },
      { name: 'Dang', pincodePrefixes: ['394'] },
      { name: 'Devbhoomi Dwarka', pincodePrefixes: ['361'] },
      { name: 'Gandhinagar', pincodePrefixes: ['382'] },
      { name: 'Gir Somnath', pincodePrefixes: ['362'] },
      { name: 'Jamnagar', pincodePrefixes: ['361'] },
      { name: 'Junagadh', pincodePrefixes: ['362'] },
      { name: 'Kheda', pincodePrefixes: ['387'] },
      { name: 'Kutch', pincodePrefixes: ['370', '370'] },
      { name: 'Mahisagar', pincodePrefixes: ['388'] },
      { name: 'Mehsana', pincodePrefixes: ['384'] },
      { name: 'Morbi', pincodePrefixes: ['363'] },
      { name: 'Narmada', pincodePrefixes: ['393'] },
      { name: 'Navsari', pincodePrefixes: ['396'] },
      { name: 'Panchmahal', pincodePrefixes: ['389'] },
      { name: 'Patan', pincodePrefixes: ['384'] },
      { name: 'Porbandar', pincodePrefixes: ['360'] },
      { name: 'Rajkot', pincodePrefixes: ['360', '363'] },
      { name: 'Sabarkantha', pincodePrefixes: ['383'] },
      { name: 'Surat', pincodePrefixes: ['394', '395'] },
      { name: 'Surendranagar', pincodePrefixes: ['363'] },
      { name: 'Tapi', pincodePrefixes: ['394'] },
      { name: 'Vadodara', pincodePrefixes: ['390', '391'] },
      { name: 'Valsad', pincodePrefixes: ['396'] },
    ],
  },
  {
    name: 'Haryana',
    code: 'HR',
    districts: [
      { name: 'Ambala', pincodePrefixes: ['133', '134'] },
      { name: 'Bhiwani', pincodePrefixes: ['127'] },
      { name: 'Charkhi Dadri', pincodePrefixes: ['127'] },
      { name: 'Faridabad', pincodePrefixes: ['121'] },
      { name: 'Fatehabad', pincodePrefixes: ['125'] },
      { name: 'Gurugram', pincodePrefixes: ['122'] },
      { name: 'Hisar', pincodePrefixes: ['125'] },
      { name: 'Jhajjar', pincodePrefixes: ['124'] },
      { name: 'Jind', pincodePrefixes: ['126'] },
      { name: 'Kaithal', pincodePrefixes: ['136'] },
      { name: 'Karnal', pincodePrefixes: ['132'] },
      { name: 'Kurukshetra', pincodePrefixes: ['136'] },
      { name: 'Mahendragarh', pincodePrefixes: ['123'] },
      { name: 'Nuh', pincodePrefixes: ['122'] },
      { name: 'Palwal', pincodePrefixes: ['121'] },
      { name: 'Panchkula', pincodePrefixes: ['134'] },
      { name: 'Panipat', pincodePrefixes: ['132'] },
      { name: 'Rewari', pincodePrefixes: ['123'] },
      { name: 'Rohtak', pincodePrefixes: ['124'] },
      { name: 'Sirsa', pincodePrefixes: ['125'] },
      { name: 'Sonipat', pincodePrefixes: ['131'] },
      { name: 'Yamunanagar', pincodePrefixes: ['135'] },
    ],
  },
  {
    name: 'Himachal Pradesh',
    code: 'HP',
    districts: [
      { name: 'Bilaspur', pincodePrefixes: ['174'] },
      { name: 'Chamba', pincodePrefixes: ['176'] },
      { name: 'Hamirpur', pincodePrefixes: ['177'] },
      { name: 'Kangra', pincodePrefixes: ['176'] },
      { name: 'Kinnaur', pincodePrefixes: ['172'] },
      { name: 'Kullu', pincodePrefixes: ['175'] },
      { name: 'Lahaul and Spiti', pincodePrefixes: ['175'] },
      { name: 'Mandi', pincodePrefixes: ['175'] },
      { name: 'Shimla', pincodePrefixes: ['171', '172'] },
      { name: 'Sirmaur', pincodePrefixes: ['173'] },
      { name: 'Solan', pincodePrefixes: ['173'] },
      { name: 'Una', pincodePrefixes: ['174'] },
    ],
  },
  {
    name: 'Jharkhand',
    code: 'JH',
    districts: [
      { name: 'Bokaro', pincodePrefixes: ['827'] },
      { name: 'Chatra', pincodePrefixes: ['825'] },
      { name: 'Deoghar', pincodePrefixes: ['814'] },
      { name: 'Dhanbad', pincodePrefixes: ['826'] },
      { name: 'Dumka', pincodePrefixes: ['814'] },
      { name: 'East Singhbhum', pincodePrefixes: ['831', '832'] },
      { name: 'Garhwa', pincodePrefixes: ['822'] },
      { name: 'Giridih', pincodePrefixes: ['815'] },
      { name: 'Godda', pincodePrefixes: ['814'] },
      { name: 'Gumla', pincodePrefixes: ['835'] },
      { name: 'Hazaribagh', pincodePrefixes: ['825'] },
      { name: 'Jamtara', pincodePrefixes: ['815'] },
      { name: 'Khunti', pincodePrefixes: ['835'] },
      { name: 'Koderma', pincodePrefixes: ['825'] },
      { name: 'Latehar', pincodePrefixes: ['829'] },
      { name: 'Lohardaga', pincodePrefixes: ['835'] },
      { name: 'Pakur', pincodePrefixes: ['816'] },
      { name: 'Palamu', pincodePrefixes: ['822'] },
      { name: 'Ramgarh', pincodePrefixes: ['829'] },
      { name: 'Ranchi', pincodePrefixes: ['834'] },
      { name: 'Sahebganj', pincodePrefixes: ['816'] },
      { name: 'Seraikela Kharsawan', pincodePrefixes: ['833'] },
      { name: 'Simdega', pincodePrefixes: ['835'] },
      { name: 'West Singhbhum', pincodePrefixes: ['833'] },
    ],
  },
  {
    name: 'Karnataka',
    code: 'KA',
    districts: [
      { name: 'Bagalkot', pincodePrefixes: ['587'] },
      { name: 'Ballari', pincodePrefixes: ['583'] },
      { name: 'Belagavi', pincodePrefixes: ['590', '591'] },
      { name: 'Bengaluru Rural', pincodePrefixes: ['562'] },
      { name: 'Bengaluru Urban', pincodePrefixes: ['560', '561'] },
      { name: 'Bidar', pincodePrefixes: ['585'] },
      { name: 'Chamarajanagar', pincodePrefixes: ['571'] },
      { name: 'Chikkaballapur', pincodePrefixes: ['562'] },
      { name: 'Chikkamagaluru', pincodePrefixes: ['577'] },
      { name: 'Chitradurga', pincodePrefixes: ['577'] },
      { name: 'Dakshina Kannada', pincodePrefixes: ['574', '575'] },
      { name: 'Davangere', pincodePrefixes: ['577'] },
      { name: 'Dharwad', pincodePrefixes: ['580'] },
      { name: 'Gadag', pincodePrefixes: ['582'] },
      { name: 'Hassan', pincodePrefixes: ['573'] },
      { name: 'Haveri', pincodePrefixes: ['581'] },
      { name: 'Kalaburagi', pincodePrefixes: ['585'] },
      { name: 'Kodagu', pincodePrefixes: ['571'] },
      { name: 'Kolar', pincodePrefixes: ['563'] },
      { name: 'Koppal', pincodePrefixes: ['583'] },
      { name: 'Mandya', pincodePrefixes: ['571'] },
      { name: 'Mysuru', pincodePrefixes: ['570', '571'] },
      { name: 'Raichur', pincodePrefixes: ['584'] },
      { name: 'Ramanagara', pincodePrefixes: ['562'] },
      { name: 'Shivamogga', pincodePrefixes: ['577'] },
      { name: 'Tumakuru', pincodePrefixes: ['572'] },
      { name: 'Udupi', pincodePrefixes: ['576'] },
      { name: 'Uttara Kannada', pincodePrefixes: ['581'] },
      { name: 'Vijayanagara', pincodePrefixes: ['583'] },
      { name: 'Vijayapura', pincodePrefixes: ['586'] },
      { name: 'Yadgir', pincodePrefixes: ['585'] },
    ],
  },
  {
    name: 'Kerala',
    code: 'KL',
    districts: [
      { name: 'Alappuzha', pincodePrefixes: ['688'] },
      { name: 'Ernakulam', pincodePrefixes: ['682', '683'] },
      { name: 'Idukki', pincodePrefixes: ['685'] },
      { name: 'Kannur', pincodePrefixes: ['670', '671'] },
      { name: 'Kasaragod', pincodePrefixes: ['671'] },
      { name: 'Kollam', pincodePrefixes: ['690', '691'] },
      { name: 'Kottayam', pincodePrefixes: ['686'] },
      { name: 'Kozhikode', pincodePrefixes: ['673'] },
      { name: 'Malappuram', pincodePrefixes: ['676'] },
      { name: 'Palakkad', pincodePrefixes: ['678'] },
      { name: 'Pathanamthitta', pincodePrefixes: ['689'] },
      { name: 'Thiruvananthapuram', pincodePrefixes: ['695'] },
      { name: 'Thrissur', pincodePrefixes: ['680'] },
      { name: 'Wayanad', pincodePrefixes: ['673'] },
    ],
  },
  {
    name: 'Madhya Pradesh',
    code: 'MP',
    districts: [
      { name: 'Agar Malwa', pincodePrefixes: ['465'] },
      { name: 'Alirajpur', pincodePrefixes: ['457'] },
      { name: 'Anuppur', pincodePrefixes: ['484'] },
      { name: 'Ashoknagar', pincodePrefixes: ['473'] },
      { name: 'Balaghat', pincodePrefixes: ['481'] },
      { name: 'Barwani', pincodePrefixes: ['451'] },
      { name: 'Betul', pincodePrefixes: ['460'] },
      { name: 'Bhind', pincodePrefixes: ['477'] },
      { name: 'Bhopal', pincodePrefixes: ['462'] },
      { name: 'Burhanpur', pincodePrefixes: ['450'] },
      { name: 'Chhatarpur', pincodePrefixes: ['471'] },
      { name: 'Chhindwara', pincodePrefixes: ['480'] },
      { name: 'Damoh', pincodePrefixes: ['470'] },
      { name: 'Datia', pincodePrefixes: ['475'] },
      { name: 'Dewas', pincodePrefixes: ['455'] },
      { name: 'Dhar', pincodePrefixes: ['454'] },
      { name: 'Dindori', pincodePrefixes: ['481'] },
      { name: 'Guna', pincodePrefixes: ['473'] },
      { name: 'Gwalior', pincodePrefixes: ['474'] },
      { name: 'Harda', pincodePrefixes: ['461'] },
      { name: 'Indore', pincodePrefixes: ['452', '453'] },
      { name: 'Jabalpur', pincodePrefixes: ['482'] },
      { name: 'Jhabua', pincodePrefixes: ['457'] },
      { name: 'Katni', pincodePrefixes: ['483'] },
      { name: 'Khandwa', pincodePrefixes: ['450'] },
      { name: 'Khargone', pincodePrefixes: ['451'] },
      { name: 'Mandla', pincodePrefixes: ['481'] },
      { name: 'Mandsaur', pincodePrefixes: ['458'] },
      { name: 'Morena', pincodePrefixes: ['476'] },
      { name: 'Narsinghpur', pincodePrefixes: ['487'] },
      { name: 'Neemuch', pincodePrefixes: ['458'] },
      { name: 'Niwari', pincodePrefixes: ['472'] },
      { name: 'Narmadapuram', pincodePrefixes: ['461'] },
      { name: 'Panna', pincodePrefixes: ['488'] },
      { name: 'Raisen', pincodePrefixes: ['464'] },
      { name: 'Rajgarh', pincodePrefixes: ['465'] },
      { name: 'Ratlam', pincodePrefixes: ['457'] },
      { name: 'Rewa', pincodePrefixes: ['486'] },
      { name: 'Sagar', pincodePrefixes: ['470'] },
      { name: 'Satna', pincodePrefixes: ['485'] },
      { name: 'Sehore', pincodePrefixes: ['466'] },
      { name: 'Seoni', pincodePrefixes: ['480'] },
      { name: 'Shahdol', pincodePrefixes: ['484'] },
      { name: 'Shajapur', pincodePrefixes: ['465'] },
      { name: 'Sheopur', pincodePrefixes: ['476'] },
      { name: 'Shivpuri', pincodePrefixes: ['473'] },
      { name: 'Sidhi', pincodePrefixes: ['486'] },
      { name: 'Singrauli', pincodePrefixes: ['486'] },
      { name: 'Tikamgarh', pincodePrefixes: ['472'] },
      { name: 'Ujjain', pincodePrefixes: ['456'] },
      { name: 'Umaria', pincodePrefixes: ['484'] },
      { name: 'Vidisha', pincodePrefixes: ['464'] },
    ],
  },
  {
    name: 'Maharashtra',
    code: 'MH',
    districts: [
      { name: 'Ahmednagar', pincodePrefixes: ['414'] },
      { name: 'Akola', pincodePrefixes: ['444'] },
      { name: 'Amravati', pincodePrefixes: ['444'] },
      { name: 'Aurangabad', pincodePrefixes: ['431'] },
      { name: 'Beed', pincodePrefixes: ['431'] },
      { name: 'Bhandara', pincodePrefixes: ['441'] },
      { name: 'Buldhana', pincodePrefixes: ['443'] },
      { name: 'Chandrapur', pincodePrefixes: ['442'] },
      { name: 'Dhule', pincodePrefixes: ['424'] },
      { name: 'Gadchiroli', pincodePrefixes: ['442'] },
      { name: 'Gondia', pincodePrefixes: ['441'] },
      { name: 'Hingoli', pincodePrefixes: ['431'] },
      { name: 'Jalgaon', pincodePrefixes: ['425'] },
      { name: 'Jalna', pincodePrefixes: ['431'] },
      { name: 'Kolhapur', pincodePrefixes: ['416'] },
      { name: 'Latur', pincodePrefixes: ['413'] },
      { name: 'Mumbai City', pincodePrefixes: ['400'] },
      { name: 'Mumbai Suburban', pincodePrefixes: ['400', '401'] },
      { name: 'Nagpur', pincodePrefixes: ['440', '441'] },
      { name: 'Nanded', pincodePrefixes: ['431'] },
      { name: 'Nandurbar', pincodePrefixes: ['425'] },
      { name: 'Nashik', pincodePrefixes: ['422', '423'] },
      { name: 'Osmanabad', pincodePrefixes: ['413'] },
      { name: 'Palghar', pincodePrefixes: ['401'] },
      { name: 'Parbhani', pincodePrefixes: ['431'] },
      { name: 'Pune', pincodePrefixes: ['411', '412'] },
      { name: 'Raigad', pincodePrefixes: ['402'] },
      { name: 'Ratnagiri', pincodePrefixes: ['415'] },
      { name: 'Sangli', pincodePrefixes: ['416'] },
      { name: 'Satara', pincodePrefixes: ['415'] },
      { name: 'Sindhudurg', pincodePrefixes: ['416'] },
      { name: 'Solapur', pincodePrefixes: ['413'] },
      { name: 'Thane', pincodePrefixes: ['400', '421'] },
      { name: 'Wardha', pincodePrefixes: ['442'] },
      { name: 'Washim', pincodePrefixes: ['444'] },
      { name: 'Yavatmal', pincodePrefixes: ['445'] },
    ],
  },
  {
    name: 'Manipur',
    code: 'MN',
    districts: [
      { name: 'Bishnupur', pincodePrefixes: ['795'] },
      { name: 'Chandel', pincodePrefixes: ['795'] },
      { name: 'Churachandpur', pincodePrefixes: ['795'] },
      { name: 'Imphal East', pincodePrefixes: ['795'] },
      { name: 'Imphal West', pincodePrefixes: ['795'] },
      { name: 'Jiribam', pincodePrefixes: ['795'] },
      { name: 'Kakching', pincodePrefixes: ['795'] },
      { name: 'Kamjong', pincodePrefixes: ['795'] },
      { name: 'Kangpokpi', pincodePrefixes: ['795'] },
      { name: 'Noney', pincodePrefixes: ['795'] },
      { name: 'Pherzawl', pincodePrefixes: ['795'] },
      { name: 'Senapati', pincodePrefixes: ['795'] },
      { name: 'Tamenglong', pincodePrefixes: ['795'] },
      { name: 'Tengnoupal', pincodePrefixes: ['795'] },
      { name: 'Thoubal', pincodePrefixes: ['795'] },
      { name: 'Ukhrul', pincodePrefixes: ['795'] },
    ],
  },
  {
    name: 'Meghalaya',
    code: 'ML',
    districts: [
      { name: 'East Garo Hills', pincodePrefixes: ['794'] },
      { name: 'East Jaintia Hills', pincodePrefixes: ['793'] },
      { name: 'East Khasi Hills', pincodePrefixes: ['793'] },
      { name: 'Eastern West Khasi Hills', pincodePrefixes: ['793'] },
      { name: 'North Garo Hills', pincodePrefixes: ['794'] },
      { name: 'Ri Bhoi', pincodePrefixes: ['793'] },
      { name: 'South Garo Hills', pincodePrefixes: ['794'] },
      { name: 'South West Garo Hills', pincodePrefixes: ['794'] },
      { name: 'South West Khasi Hills', pincodePrefixes: ['793'] },
      { name: 'West Garo Hills', pincodePrefixes: ['794'] },
      { name: 'West Jaintia Hills', pincodePrefixes: ['793'] },
      { name: 'West Khasi Hills', pincodePrefixes: ['793'] },
    ],
  },
  {
    name: 'Mizoram',
    code: 'MZ',
    districts: [
      { name: 'Aizawl', pincodePrefixes: ['796'] },
      { name: 'Champhai', pincodePrefixes: ['796'] },
      { name: 'Hnahthial', pincodePrefixes: ['796'] },
      { name: 'Khawzawl', pincodePrefixes: ['796'] },
      { name: 'Kolasib', pincodePrefixes: ['796'] },
      { name: 'Lawngtlai', pincodePrefixes: ['796'] },
      { name: 'Lunglei', pincodePrefixes: ['796'] },
      { name: 'Mamit', pincodePrefixes: ['796'] },
      { name: 'Saitual', pincodePrefixes: ['796'] },
      { name: 'Serchhip', pincodePrefixes: ['796'] },
      { name: 'Siaha', pincodePrefixes: ['796'] },
    ],
  },
  {
    name: 'Nagaland',
    code: 'NL',
    districts: [
      { name: 'Chumoukedima', pincodePrefixes: ['797'] },
      { name: 'Dimapur', pincodePrefixes: ['797'] },
      { name: 'Kiphire', pincodePrefixes: ['798'] },
      { name: 'Kohima', pincodePrefixes: ['797'] },
      { name: 'Longleng', pincodePrefixes: ['798'] },
      { name: 'Mokokchung', pincodePrefixes: ['798'] },
      { name: 'Mon', pincodePrefixes: ['798'] },
      { name: 'Niuland', pincodePrefixes: ['797'] },
      { name: 'Noklak', pincodePrefixes: ['798'] },
      { name: 'Peren', pincodePrefixes: ['797'] },
      { name: 'Phek', pincodePrefixes: ['797'] },
      { name: 'Shamator', pincodePrefixes: ['798'] },
      { name: 'Tseminyü', pincodePrefixes: ['797'] },
      { name: 'Tuensang', pincodePrefixes: ['798'] },
      { name: 'Wokha', pincodePrefixes: ['797'] },
      { name: 'Zunheboto', pincodePrefixes: ['798'] },
    ],
  },
  {
    name: 'Odisha',
    code: 'OD',
    districts: [
      { name: 'Angul', pincodePrefixes: ['759'] },
      { name: 'Balangir', pincodePrefixes: ['767'] },
      { name: 'Balasore', pincodePrefixes: ['756'] },
      { name: 'Bargarh', pincodePrefixes: ['768'] },
      { name: 'Bhadrak', pincodePrefixes: ['756'] },
      { name: 'Boudh', pincodePrefixes: ['762'] },
      { name: 'Cuttack', pincodePrefixes: ['753', '754'] },
      { name: 'Deogarh', pincodePrefixes: ['768'] },
      { name: 'Dhenkanal', pincodePrefixes: ['759'] },
      { name: 'Gajapati', pincodePrefixes: ['761'] },
      { name: 'Ganjam', pincodePrefixes: ['760', '761'] },
      { name: 'Jagatsinghpur', pincodePrefixes: ['754'] },
      { name: 'Jajpur', pincodePrefixes: ['755'] },
      { name: 'Jharsuguda', pincodePrefixes: ['768'] },
      { name: 'Kalahandi', pincodePrefixes: ['766'] },
      { name: 'Kandhamal', pincodePrefixes: ['762'] },
      { name: 'Kendrapara', pincodePrefixes: ['754'] },
      { name: 'Kendujhar', pincodePrefixes: ['758'] },
      { name: 'Khurda', pincodePrefixes: ['752'] },
      { name: 'Koraput', pincodePrefixes: ['763'] },
      { name: 'Malkangiri', pincodePrefixes: ['764'] },
      { name: 'Mayurbhanj', pincodePrefixes: ['757'] },
      { name: 'Nabarangpur', pincodePrefixes: ['764'] },
      { name: 'Nayagarh', pincodePrefixes: ['752'] },
      { name: 'Nuapada', pincodePrefixes: ['766'] },
      { name: 'Puri', pincodePrefixes: ['752'] },
      { name: 'Rayagada', pincodePrefixes: ['765'] },
      { name: 'Sambalpur', pincodePrefixes: ['768'] },
      { name: 'Sonepur', pincodePrefixes: ['767'] },
      { name: 'Sundargarh', pincodePrefixes: ['770'] },
    ],
  },
  {
    name: 'Punjab',
    code: 'PB',
    districts: [
      { name: 'Amritsar', pincodePrefixes: ['143'] },
      { name: 'Barnala', pincodePrefixes: ['148'] },
      { name: 'Bathinda', pincodePrefixes: ['151'] },
      { name: 'Faridkot', pincodePrefixes: ['151'] },
      { name: 'Fatehgarh Sahib', pincodePrefixes: ['140'] },
      { name: 'Fazilka', pincodePrefixes: ['152'] },
      { name: 'Ferozepur', pincodePrefixes: ['152'] },
      { name: 'Gurdaspur', pincodePrefixes: ['143'] },
      { name: 'Hoshiarpur', pincodePrefixes: ['146'] },
      { name: 'Jalandhar', pincodePrefixes: ['144'] },
      { name: 'Kapurthala', pincodePrefixes: ['144'] },
      { name: 'Ludhiana', pincodePrefixes: ['141', '142'] },
      { name: 'Malerkotla', pincodePrefixes: ['148'] },
      { name: 'Mansa', pincodePrefixes: ['151'] },
      { name: 'Moga', pincodePrefixes: ['142'] },
      { name: 'Mohali', pincodePrefixes: ['140'] },
      { name: 'Muktsar', pincodePrefixes: ['152'] },
      { name: 'Nawanshahr', pincodePrefixes: ['144'] },
      { name: 'Pathankot', pincodePrefixes: ['145'] },
      { name: 'Patiala', pincodePrefixes: ['147'] },
      { name: 'Rupnagar', pincodePrefixes: ['140'] },
      { name: 'Sangrur', pincodePrefixes: ['148'] },
      { name: 'Tarn Taran', pincodePrefixes: ['143'] },
    ],
  },
  {
    name: 'Rajasthan',
    code: 'RJ',
    districts: [
      { name: 'Ajmer', pincodePrefixes: ['305'] },
      { name: 'Alwar', pincodePrefixes: ['301'] },
      { name: 'Banswara', pincodePrefixes: ['327'] },
      { name: 'Baran', pincodePrefixes: ['325'] },
      { name: 'Barmer', pincodePrefixes: ['344'] },
      { name: 'Bharatpur', pincodePrefixes: ['321'] },
      { name: 'Bhilwara', pincodePrefixes: ['311'] },
      { name: 'Bikaner', pincodePrefixes: ['334'] },
      { name: 'Bundi', pincodePrefixes: ['323'] },
      { name: 'Chittorgarh', pincodePrefixes: ['312'] },
      { name: 'Churu', pincodePrefixes: ['331'] },
      { name: 'Dausa', pincodePrefixes: ['303'] },
      { name: 'Dholpur', pincodePrefixes: ['328'] },
      { name: 'Dungarpur', pincodePrefixes: ['314'] },
      { name: 'Hanumangarh', pincodePrefixes: ['335'] },
      { name: 'Jaipur', pincodePrefixes: ['302', '303'] },
      { name: 'Jaisalmer', pincodePrefixes: ['345'] },
      { name: 'Jalore', pincodePrefixes: ['343'] },
      { name: 'Jhalawar', pincodePrefixes: ['326'] },
      { name: 'Jhunjhunu', pincodePrefixes: ['333'] },
      { name: 'Jodhpur', pincodePrefixes: ['342'] },
      { name: 'Karauli', pincodePrefixes: ['322'] },
      { name: 'Kota', pincodePrefixes: ['324'] },
      { name: 'Nagaur', pincodePrefixes: ['341'] },
      { name: 'Pali', pincodePrefixes: ['306'] },
      { name: 'Pratapgarh', pincodePrefixes: ['312'] },
      { name: 'Rajsamand', pincodePrefixes: ['313'] },
      { name: 'Sawai Madhopur', pincodePrefixes: ['322'] },
      { name: 'Sikar', pincodePrefixes: ['332'] },
      { name: 'Sirohi', pincodePrefixes: ['307'] },
      { name: 'Sri Ganganagar', pincodePrefixes: ['335'] },
      { name: 'Tonk', pincodePrefixes: ['304'] },
      { name: 'Udaipur', pincodePrefixes: ['313'] },
    ],
  },
  {
    name: 'Sikkim',
    code: 'SK',
    districts: [
      { name: 'East Sikkim', pincodePrefixes: ['737'] },
      { name: 'North Sikkim', pincodePrefixes: ['737'] },
      { name: 'Pakyong', pincodePrefixes: ['737'] },
      { name: 'Soreng', pincodePrefixes: ['737'] },
      { name: 'South Sikkim', pincodePrefixes: ['737'] },
      { name: 'West Sikkim', pincodePrefixes: ['737'] },
    ],
  },
  {
    name: 'Tamil Nadu',
    code: 'TN',
    districts: [
      { name: 'Ariyalur', pincodePrefixes: ['621'] },
      { name: 'Chengalpattu', pincodePrefixes: ['603'] },
      { name: 'Chennai', pincodePrefixes: ['600', '601', '602'] },
      { name: 'Coimbatore', pincodePrefixes: ['641', '642'] },
      { name: 'Cuddalore', pincodePrefixes: ['607'] },
      { name: 'Dharmapuri', pincodePrefixes: ['636'] },
      { name: 'Dindigul', pincodePrefixes: ['624'] },
      { name: 'Erode', pincodePrefixes: ['638'] },
      { name: 'Kallakurichi', pincodePrefixes: ['606'] },
      { name: 'Kancheepuram', pincodePrefixes: ['631'] },
      { name: 'Kanyakumari', pincodePrefixes: ['629'] },
      { name: 'Karur', pincodePrefixes: ['639'] },
      { name: 'Krishnagiri', pincodePrefixes: ['635'] },
      { name: 'Madurai', pincodePrefixes: ['625'] },
      { name: 'Mayiladuthurai', pincodePrefixes: ['609'] },
      { name: 'Nagapattinam', pincodePrefixes: ['611'] },
      { name: 'Namakkal', pincodePrefixes: ['637'] },
      { name: 'Nilgiris', pincodePrefixes: ['643'] },
      { name: 'Perambalur', pincodePrefixes: ['621'] },
      { name: 'Pudukkottai', pincodePrefixes: ['622'] },
      { name: 'Ramanathapuram', pincodePrefixes: ['623'] },
      { name: 'Ranipet', pincodePrefixes: ['632'] },
      { name: 'Salem', pincodePrefixes: ['636'] },
      { name: 'Sivaganga', pincodePrefixes: ['623'] },
      { name: 'Tenkasi', pincodePrefixes: ['627'] },
      { name: 'Thanjavur', pincodePrefixes: ['613'] },
      { name: 'Theni', pincodePrefixes: ['625'] },
      { name: 'Thoothukudi', pincodePrefixes: ['628'] },
      { name: 'Tiruchirappalli', pincodePrefixes: ['620'] },
      { name: 'Tirunelveli', pincodePrefixes: ['627'] },
      { name: 'Tirupathur', pincodePrefixes: ['635'] },
      { name: 'Tiruppur', pincodePrefixes: ['641'] },
      { name: 'Tiruvallur', pincodePrefixes: ['602'] },
      { name: 'Tiruvannamalai', pincodePrefixes: ['606'] },
      { name: 'Tiruvarur', pincodePrefixes: ['610'] },
      { name: 'Vellore', pincodePrefixes: ['632'] },
      { name: 'Viluppuram', pincodePrefixes: ['605'] },
      { name: 'Virudhunagar', pincodePrefixes: ['626'] },
    ],
  },
  {
    name: 'Telangana',
    code: 'TG',
    districts: [
      { name: 'Adilabad', pincodePrefixes: ['504'] },
      { name: 'Bhadradri Kothagudem', pincodePrefixes: ['507'] },
      { name: 'Hanumakonda', pincodePrefixes: ['506'] },
      { name: 'Hyderabad', pincodePrefixes: ['500', '501'] },
      { name: 'Jagtial', pincodePrefixes: ['505'] },
      { name: 'Jangaon', pincodePrefixes: ['506'] },
      { name: 'Jayashankar Bhupalpally', pincodePrefixes: ['506'] },
      { name: 'Jogulamba Gadwal', pincodePrefixes: ['509'] },
      { name: 'Kamareddy', pincodePrefixes: ['503'] },
      { name: 'Karimnagar', pincodePrefixes: ['505'] },
      { name: 'Khammam', pincodePrefixes: ['507'] },
      { name: 'Komaram Bheem Asifabad', pincodePrefixes: ['504'] },
      { name: 'Mahabubabad', pincodePrefixes: ['506'] },
      { name: 'Mahabubnagar', pincodePrefixes: ['509'] },
      { name: 'Mancherial', pincodePrefixes: ['504'] },
      { name: 'Medak', pincodePrefixes: ['502'] },
      { name: 'Medchal-Malkajgiri', pincodePrefixes: ['500', '501'] },
      { name: 'Mulugu', pincodePrefixes: ['506'] },
      { name: 'Nagarkurnool', pincodePrefixes: ['509'] },
      { name: 'Nalgonda', pincodePrefixes: ['508'] },
      { name: 'Narayanpet', pincodePrefixes: ['509'] },
      { name: 'Nirmal', pincodePrefixes: ['504'] },
      { name: 'Nizamabad', pincodePrefixes: ['503'] },
      { name: 'Peddapalli', pincodePrefixes: ['505'] },
      { name: 'Rajanna Sircilla', pincodePrefixes: ['505'] },
      { name: 'Rangareddy', pincodePrefixes: ['500', '501'] },
      { name: 'Sangareddy', pincodePrefixes: ['502'] },
      { name: 'Siddipet', pincodePrefixes: ['502'] },
      { name: 'Suryapet', pincodePrefixes: ['508'] },
      { name: 'Vikarabad', pincodePrefixes: ['501'] },
      { name: 'Wanaparthy', pincodePrefixes: ['509'] },
      { name: 'Warangal', pincodePrefixes: ['506'] },
      { name: 'Yadadri Bhuvanagiri', pincodePrefixes: ['508'] },
    ],
  },
  {
    name: 'Tripura',
    code: 'TR',
    districts: [
      { name: 'Dhalai', pincodePrefixes: ['799'] },
      { name: 'Gomati', pincodePrefixes: ['799'] },
      { name: 'Khowai', pincodePrefixes: ['799'] },
      { name: 'North Tripura', pincodePrefixes: ['799'] },
      { name: 'Sepahijala', pincodePrefixes: ['799'] },
      { name: 'South Tripura', pincodePrefixes: ['799'] },
      { name: 'Unakoti', pincodePrefixes: ['799'] },
      { name: 'West Tripura', pincodePrefixes: ['799'] },
    ],
  },
  {
    name: 'Uttar Pradesh',
    code: 'UP',
    districts: [
      { name: 'Agra', pincodePrefixes: ['282'] },
      { name: 'Aligarh', pincodePrefixes: ['202'] },
      { name: 'Ambedkar Nagar', pincodePrefixes: ['224'] },
      { name: 'Amethi', pincodePrefixes: ['227'] },
      { name: 'Amroha', pincodePrefixes: ['244'] },
      { name: 'Auraiya', pincodePrefixes: ['206'] },
      { name: 'Ayodhya', pincodePrefixes: ['224'] },
      { name: 'Azamgarh', pincodePrefixes: ['276'] },
      { name: 'Baghpat', pincodePrefixes: ['250'] },
      { name: 'Bahraich', pincodePrefixes: ['271'] },
      { name: 'Ballia', pincodePrefixes: ['277'] },
      { name: 'Balrampur', pincodePrefixes: ['271'] },
      { name: 'Banda', pincodePrefixes: ['210'] },
      { name: 'Barabanki', pincodePrefixes: ['225'] },
      { name: 'Bareilly', pincodePrefixes: ['243'] },
      { name: 'Basti', pincodePrefixes: ['272'] },
      { name: 'Bhadohi', pincodePrefixes: ['221'] },
      { name: 'Bijnor', pincodePrefixes: ['246'] },
      { name: 'Budaun', pincodePrefixes: ['243'] },
      { name: 'Bulandshahr', pincodePrefixes: ['203'] },
      { name: 'Chandauli', pincodePrefixes: ['232'] },
      { name: 'Chitrakoot', pincodePrefixes: ['210'] },
      { name: 'Deoria', pincodePrefixes: ['274'] },
      { name: 'Etah', pincodePrefixes: ['207'] },
      { name: 'Etawah', pincodePrefixes: ['206'] },
      { name: 'Farrukhabad', pincodePrefixes: ['209'] },
      { name: 'Fatehpur', pincodePrefixes: ['212'] },
      { name: 'Firozabad', pincodePrefixes: ['283'] },
      { name: 'Gautam Buddha Nagar', pincodePrefixes: ['201'] },
      { name: 'Ghaziabad', pincodePrefixes: ['201'] },
      { name: 'Ghazipur', pincodePrefixes: ['233'] },
      { name: 'Gonda', pincodePrefixes: ['271'] },
      { name: 'Gorakhpur', pincodePrefixes: ['273'] },
      { name: 'Hamirpur', pincodePrefixes: ['210'] },
      { name: 'Hapur', pincodePrefixes: ['245'] },
      { name: 'Hardoi', pincodePrefixes: ['241'] },
      { name: 'Hathras', pincodePrefixes: ['204'] },
      { name: 'Jalaun', pincodePrefixes: ['285'] },
      { name: 'Jaunpur', pincodePrefixes: ['222'] },
      { name: 'Jhansi', pincodePrefixes: ['284'] },
      { name: 'Kannauj', pincodePrefixes: ['209'] },
      { name: 'Kanpur Dehat', pincodePrefixes: ['209'] },
      { name: 'Kanpur Nagar', pincodePrefixes: ['208'] },
      { name: 'Kasganj', pincodePrefixes: ['207'] },
      { name: 'Kaushambi', pincodePrefixes: ['212'] },
      { name: 'Kushinagar', pincodePrefixes: ['274'] },
      { name: 'Lakhimpur Kheri', pincodePrefixes: ['262'] },
      { name: 'Lalitpur', pincodePrefixes: ['284'] },
      { name: 'Lucknow', pincodePrefixes: ['226', '227'] },
      { name: 'Mahoba', pincodePrefixes: ['210'] },
      { name: 'Mahrajganj', pincodePrefixes: ['273'] },
      { name: 'Mainpuri', pincodePrefixes: ['205'] },
      { name: 'Mathura', pincodePrefixes: ['281'] },
      { name: 'Mau', pincodePrefixes: ['275'] },
      { name: 'Meerut', pincodePrefixes: ['250'] },
      { name: 'Mirzapur', pincodePrefixes: ['231'] },
      { name: 'Moradabad', pincodePrefixes: ['244'] },
      { name: 'Muzaffarnagar', pincodePrefixes: ['251'] },
      { name: 'Pilibhit', pincodePrefixes: ['262'] },
      { name: 'Pratapgarh', pincodePrefixes: ['230'] },
      { name: 'Prayagraj', pincodePrefixes: ['211', '212'] },
      { name: 'Raebareli', pincodePrefixes: ['229'] },
      { name: 'Rampur', pincodePrefixes: ['244'] },
      { name: 'Saharanpur', pincodePrefixes: ['247'] },
      { name: 'Sambhal', pincodePrefixes: ['244'] },
      { name: 'Sant Kabir Nagar', pincodePrefixes: ['272'] },
      { name: 'Shahjahanpur', pincodePrefixes: ['242'] },
      { name: 'Shamli', pincodePrefixes: ['247'] },
      { name: 'Shravasti', pincodePrefixes: ['271'] },
      { name: 'Siddharthnagar', pincodePrefixes: ['272'] },
      { name: 'Sitapur', pincodePrefixes: ['261'] },
      { name: 'Sonbhadra', pincodePrefixes: ['231'] },
      { name: 'Sultanpur', pincodePrefixes: ['228'] },
      { name: 'Unnao', pincodePrefixes: ['209'] },
      { name: 'Varanasi', pincodePrefixes: ['221'] },
    ],
  },
  {
    name: 'Uttarakhand',
    code: 'UT',
    districts: [
      { name: 'Almora', pincodePrefixes: ['263'] },
      { name: 'Bageshwar', pincodePrefixes: ['263'] },
      { name: 'Chamoli', pincodePrefixes: ['246'] },
      { name: 'Champawat', pincodePrefixes: ['262'] },
      { name: 'Dehradun', pincodePrefixes: ['248'] },
      { name: 'Haridwar', pincodePrefixes: ['249'] },
      { name: 'Nainital', pincodePrefixes: ['263'] },
      { name: 'Pauri Garhwal', pincodePrefixes: ['246'] },
      { name: 'Pithoragarh', pincodePrefixes: ['262'] },
      { name: 'Rudraprayag', pincodePrefixes: ['246'] },
      { name: 'Tehri Garhwal', pincodePrefixes: ['249'] },
      { name: 'Udham Singh Nagar', pincodePrefixes: ['263'] },
      { name: 'Uttarkashi', pincodePrefixes: ['249'] },
    ],
  },
  {
    name: 'West Bengal',
    code: 'WB',
    districts: [
      { name: 'Alipurduar', pincodePrefixes: ['736'] },
      { name: 'Bankura', pincodePrefixes: ['722'] },
      { name: 'Birbhum', pincodePrefixes: ['731'] },
      { name: 'Cooch Behar', pincodePrefixes: ['736'] },
      { name: 'Dakshin Dinajpur', pincodePrefixes: ['733'] },
      { name: 'Darjeeling', pincodePrefixes: ['734'] },
      { name: 'Hooghly', pincodePrefixes: ['712'] },
      { name: 'Howrah', pincodePrefixes: ['711'] },
      { name: 'Jalpaiguri', pincodePrefixes: ['735'] },
      { name: 'Jhargram', pincodePrefixes: ['721'] },
      { name: 'Kalimpong', pincodePrefixes: ['734'] },
      { name: 'Kolkata', pincodePrefixes: ['700', '701'] },
      { name: 'Malda', pincodePrefixes: ['732'] },
      { name: 'Murshidabad', pincodePrefixes: ['742'] },
      { name: 'Nadia', pincodePrefixes: ['741'] },
      { name: 'North 24 Parganas', pincodePrefixes: ['700', '743'] },
      { name: 'Paschim Bardhaman', pincodePrefixes: ['713'] },
      { name: 'Paschim Medinipur', pincodePrefixes: ['721'] },
      { name: 'Purba Bardhaman', pincodePrefixes: ['713'] },
      { name: 'Purba Medinipur', pincodePrefixes: ['721'] },
      { name: 'Purulia', pincodePrefixes: ['723'] },
      { name: 'South 24 Parganas', pincodePrefixes: ['743', '744'] },
      { name: 'Uttar Dinajpur', pincodePrefixes: ['733'] },
    ],
  },
  {
    name: 'Delhi',
    code: 'DL',
    districts: [
      { name: 'Central Delhi', pincodePrefixes: ['110'] },
      { name: 'East Delhi', pincodePrefixes: ['110'] },
      { name: 'New Delhi', pincodePrefixes: ['110'] },
      { name: 'North Delhi', pincodePrefixes: ['110'] },
      { name: 'North East Delhi', pincodePrefixes: ['110'] },
      { name: 'North West Delhi', pincodePrefixes: ['110'] },
      { name: 'Shahdara', pincodePrefixes: ['110'] },
      { name: 'South Delhi', pincodePrefixes: ['110'] },
      { name: 'South East Delhi', pincodePrefixes: ['110'] },
      { name: 'South West Delhi', pincodePrefixes: ['110'] },
      { name: 'West Delhi', pincodePrefixes: ['110'] },
    ],
  },
  {
    name: 'Jammu and Kashmir',
    code: 'JK',
    districts: [
      { name: 'Anantnag', pincodePrefixes: ['192'] },
      { name: 'Bandipora', pincodePrefixes: ['193'] },
      { name: 'Baramulla', pincodePrefixes: ['193'] },
      { name: 'Budgam', pincodePrefixes: ['191'] },
      { name: 'Doda', pincodePrefixes: ['182'] },
      { name: 'Ganderbal', pincodePrefixes: ['191'] },
      { name: 'Jammu', pincodePrefixes: ['180', '181'] },
      { name: 'Kathua', pincodePrefixes: ['184'] },
      { name: 'Kishtwar', pincodePrefixes: ['182'] },
      { name: 'Kulgam', pincodePrefixes: ['192'] },
      { name: 'Kupwara', pincodePrefixes: ['193'] },
      { name: 'Poonch', pincodePrefixes: ['185'] },
      { name: 'Pulwama', pincodePrefixes: ['192'] },
      { name: 'Rajouri', pincodePrefixes: ['185'] },
      { name: 'Ramban', pincodePrefixes: ['182'] },
      { name: 'Reasi', pincodePrefixes: ['182'] },
      { name: 'Samba', pincodePrefixes: ['184'] },
      { name: 'Shopian', pincodePrefixes: ['192'] },
      { name: 'Srinagar', pincodePrefixes: ['190', '191'] },
      { name: 'Udhampur', pincodePrefixes: ['182'] },
    ],
  },
  {
    name: 'Ladakh',
    code: 'LA',
    districts: [
      { name: 'Kargil', pincodePrefixes: ['194'] },
      { name: 'Leh', pincodePrefixes: ['194'] },
    ],
  },
  {
    name: 'Andaman and Nicobar Islands',
    code: 'AN',
    districts: [
      { name: 'Nicobar', pincodePrefixes: ['744'] },
      { name: 'North and Middle Andaman', pincodePrefixes: ['744'] },
      { name: 'South Andaman', pincodePrefixes: ['744'] },
    ],
  },
  {
    name: 'Chandigarh',
    code: 'CH',
    districts: [
      { name: 'Chandigarh', pincodePrefixes: ['160'] },
    ],
  },
  {
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    code: 'DN',
    districts: [
      { name: 'Dadra and Nagar Haveli', pincodePrefixes: ['396'] },
      { name: 'Daman', pincodePrefixes: ['396'] },
      { name: 'Diu', pincodePrefixes: ['362'] },
    ],
  },
  {
    name: 'Lakshadweep',
    code: 'LD',
    districts: [
      { name: 'Lakshadweep', pincodePrefixes: ['682'] },
    ],
  },
  {
    name: 'Puducherry',
    code: 'PY',
    districts: [
      { name: 'Karaikal', pincodePrefixes: ['609'] },
      { name: 'Mahe', pincodePrefixes: ['673'] },
      { name: 'Puducherry', pincodePrefixes: ['605'] },
      { name: 'Yanam', pincodePrefixes: ['533'] },
    ],
  },
];

/**
 * Helper to get districts for a state
 */
export const getDistrictsByState = (stateName: string): District[] => {
  const state = INDIA_STATES.find((s) => s.name === stateName);
  return state?.districts || [];
};

/**
 * Get all state names
 */
export const getStateNames = (): string[] => {
  return INDIA_STATES.map((state) => state.name);
};

/**
 * Validate pincode format and length
 */
export const validatePincode = (pincode: string): boolean => {
  return /^\d{6}$/.test(pincode);
};

/**
 * Validate phone number (Indian format)
 */
export const validatePhoneNumber = (phone: string): boolean => {
  // Remove all non-digits
  const digits = phone.replace(/\D/g, '');
  // Must be exactly 10 digits and start with valid range
  return /^[6-9]\d{9}$/.test(digits);
};

/**
 * Format phone number for display
 */
export const formatPhoneNumber = (phone: string): string => {
  const digits = phone.replace(/\D/g, '');
  if (digits.length === 10) {
    return `+91 ${digits.slice(0, 5)} ${digits.slice(5)}`;
  }
  return phone;
};
